import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Link from "next/link";

export default function Home() {
  const router = useRouter();

  const NEXT_PUBLIC_TEXT = process.env.NEXT_PUBLIC_TEXT;
  console.log("NEXT_PUBLIC_TEXT: ", NEXT_PUBLIC_TEXT);
  const APP_ENV = process.env.APP_ENV;
  const NODE_ENV = process.env.NODE_ENV;
  console.log("NODE_ENV: ", NODE_ENV);
  console.log("APP_ENV: ", APP_ENV);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>첫번쨰다</div>
      {/* <div>{APP_ENV}</div> */}
      {/* <div>{NODE_ENV}</div> */}
      {/* <div>{APP_ENV}</div> */}
      <div>{NEXT_PUBLIC_TEXT}</div>

      <button onClick={() => router.push("/profile")}>프로필</button>
      <button onClick={() => router.push("/todo")}>투두리스트</button>

      <li>
        <Link href="/static-props">
          <>getStatic-props 페이지</>
        </Link>
      </li>
      <li>
        <Link href="/auto">자동 정적 생성 페이지</Link>
      </li>
    </div>
  );
}
