import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const local = process.env.NEXT_PUBLIC_TEST;
  console.log("NEXT_PUBLIC_TEST: ", local);

  const NODE_ENV = process.env.NODE_ENV;
  const APP_ENV = process.env.APP_ENV;
  console.log("APP_ENV: ", APP_ENV);

  const Server_PORT = process.env.NEXT_PUBLIC_PORT;
  console.log("Server_PORT: ", Server_PORT);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>local{local}</div> */}
      {/* <div>APP_ENV{APP_ENV}</div> */}
      {/* <div>point{point}</div> */}

      {/* <div>id{point}</div> */}
      <button onClick={() => router.push("/profile")}>프로필</button>
      <button onClick={() => router.push("/todo")}>투두리스트</button>
    </div>
  );
}
